FORMAT: 1A
HOST: http://private-7bed3-locationlogger.apiary-mock.com

# location-tracker

location tracker is a project realized at Silesian University of Technology on the 6th semester.
The application collects tracks with gps points location and displays it on the map and additional
information based on collected data. User is able to manage saved tracks and devices related 
to the application. Any device added to the user profile is able to send data to the application.


## Token [/token]

### Refresh token [GET]

Refresh user token

+ Response 200 (application/json)
       
        {
            "token": "302cfd16-339f-11e8-b467-0ed5f89f718b" 
        }

## User information [/me]

### User information [GET]

Fetch user data

+ Response 200 (application/json)
        
        {
            "id": 1,
            "email": "user@email.com"
        }
        

## Tracks [/tracks]

### Tracks collection [GET]

Fetch all user trancks 

+ Response 200

        [
            {
                "id": 1,
                "name: "Test track",
                "points":[
                    {"lat": 25.00, "lng": 22.22}
                ]
            }
        ]