FORMAT: 1A
HOST: http://private-7bed3-locationlogger.apiary-mock.com

# location-tracker

location tracker is a project realized at Silesian University of Technology on the 6th semester.
The application collects tracks with gps points location and displays it on the map and additional
information based on collected data. User is able to manage saved tracks and devices related 
to the application. Any device added to the user profile is able to send data to the application.

## Registration [/user/register]

Registration new user to the system

### Register user [POST]

+ Request (application/json)

        {
            "username": "user.name@userservice.com",
            "password": "user-super-password"
        }
        
+ Response 201 (application/json)

    + Attributes (User)


## Login [/user/login]

Login as an existing user 

### Login user [POST]

+ Request (application/json)

        {
            "username": "user.name@userservice.com",
            "password": "user-super-password"
        }
        
+ Response 200 (application/json)

    + Attributes (User)

## User data [/me]

Get user data

### Get user data [GET]

+ Response 200 (application/json)

    + Attributes (User)

## Devices list [/devices]

Get list of all users devices

### Get list of devices [GET]

+ Response 200 (application/json)

    + Attributes (array[Device Nexus ,Device Iphone])

## Device [/device/{device_id}]

Manage device

+ Parameters
    + device_id (number, required) - id of device

### Get device details [GET]

Get device details by device id

+ Response 200 (application/json)

    + Attributes (Device Nexus)
    

### Update device details [PATCH]

Update device details

+ Request (application/json)

        {
            "name": "LG Nexus 6X",
        }

+ Response 200 (application/json)

    + Body
    
            {
                "id": 1,
                "name": "LG Nexus 6X",
                "uuid": "21bb24d8352511e8b4670ed5f89f718b",
                "removed": false
            }

### Delete device [DELETE]

Delete device

+ Response 200 (application/json)

    + Body
            
            {
                "id": 1,
                "name": "LG Nexus 5X",
                "uuid": "21bb24d8352511e8b4670ed5f89f718b",
                "removed": true
            }

## Tracks list [/tracks]

Get list of tracks

### Get tracks list [GET]

+ Response 200 (application/json)

    + Attributes (array[Track1,Track2,Track3])

## Track details [/track/{id}]

Get track details

+ Parameters
    + id (number, required) - id of track

### Get track details [GET]

+ Response 200 (application/json)

    + Attributes (Track1)
        + points (array[Point1, Point2, Point3]) (array)

# Data Structures

## User (object)
+ id: 1 (number)
+ username: user.name@userservice.com (string)
+ removed: false (boolean)

## Device Nexus (object)
+ id: 1 (number)
+ name: LG Nexus 5X (string)
+ uuid: 21bb24d8352511e8b4670ed5f89f718b (string)
+ removed: false (boolean)

## Device Iphone (object)
+ id: 2 (number)
+ name: Iphone 5s (string)
+ uuid: 21bb2776352511e8b4670ed5f89f718b (string)
+ removed: false (boolean)

## Track1 (object)
+ id: 1 (number)
+ device_id: 2 (number)
+ date: 2012-06-25T17:43:20.000+0000 (timestamp) 
+ distance: 36018.942 (number)
+ duration: 01:29:58
+ startTime: 2012-06-25T17:43:20.000+0000 (timestamp)
+ endTime: 2012-06-25T19:13:18.000+0000 (timestamp)
+ minSpeed: 1.0 (number)
+ maxSpeed: 41.06 (number)
+ avgSpeed: 28.42 (number)
+ minAltitude: 223.25 (number)
+ maxAltitude: 283.75 (number)
+ avgAltitude: 246.742 (number)

## Track2 (object)
+ id: 2 (number)
+ name: Test name track 2 (string)
+ device_id: 2 (number)
+ date: 2012-06-25T17:43:20.000+0000 (timestamp) 
+ distance: 36018.942 (number)
+ duration: 01:29:58
+ startTime: 2012-06-25T17:43:20.000+0000 (timestamp)
+ endTime: 2012-06-25T19:13:18.000+0000 (timestamp)
+ minSpeed: 1.0 (number)
+ maxSpeed: 41.06 (number)
+ avgSpeed: 28.42 (number)
+ minAltitude: 223.25 (number)
+ maxAltitude: 283.75 (number)
+ avgAltitude: 246.742 (number)

## Track3 (object)
+ id: 3 (number)
+ name: Test name track 3 (string)
+ device_id: 2 (number)
+ date: 2012-06-25T17:43:20.000+0000 (timestamp) 
+ distance: 36018.942 (number)
+ duration: 01:29:58
+ startTime: 2012-06-25T17:43:20.000+0000 (timestamp)
+ endTime: 2012-06-25T19:13:18.000+0000 (timestamp)
+ minSpeed: 1.0 (number)
+ maxSpeed: 41.06 (number)
+ avgSpeed: 28.42 (number)
+ minAltitude: 223.25 (number)
+ maxAltitude: 283.75 (number)
+ avgAltitude: 246.742 (number)


## Point1 (object)
+ id: 1 (number)
+ timestamp: 123412341 (number)
+ latitude: 50.3235 (number)
+ longitude: 40.2335 (number)
+ altitude: 44.23241 (number)
+ speed: 40 (number)
+ direction: 3 (number)

## Point2 (object)
+ id: 2 (number)
+ timestamp: 123412342 (number)
+ latitude: 50.3235 (number)
+ longitude: 40.2335 (number)
+ altitude: 44.23241 (number)
+ speed: 40 (number)
+ direction: 2 (number)

## Point3 (object)
+ id: 3 (number)
+ timestamp: 123412343 (number)
+ latitude: 50.3236 (number)
+ longitude: 40.2335 (number)
+ altitude: 44.23241 (number)
+ speed: 40 (number)
+ direction: 1 (number)

## Point4 (object)
+ id: 4 (number)
+ timestamp: 123412344 (number)
+ latitude: 50.3237 (number)
+ longitude: 40.2335 (number)
+ altitude: 44.23241 (number)
+ speed: 40 (number)
+ direction: 4 (number)